### ISSUE TITLE
simple example writing onto existing numpy buffer dies

### ISSUE THREAD

**Issue by stuaxo** [SimonSapin/cairocffi#51]
This example of dies -

http://stackoverflow.com/questions/10031580/how-to-write-simple-geometric-shapes-into-numpy-arrays/10031877#10031877

Code
```python
import numpy
import cairo
#import cairocffi as cairo
import math
data = numpy.zeros((200, 200, 4), dtype=numpy.uint8)
surface = cairo.ImageSurface.create_for_data(
    data, cairo.FORMAT_ARGB32, 200, 200)
cr = cairo.Context(surface)

# fill with solid white
cr.set_source_rgb(1.0, 1.0, 1.0)
cr.paint()

# draw red circle
cr.arc(100, 100, 80, 0, 2*math.pi)
cr.set_line_width(3)
cr.set_source_rgb(1.0, 0.0, 0.0)
cr.stroke()

# write output
print data[38:48, 38:48, 0]
surface.write_to_png("circle.png")
```
Output in pycairo:
```python
## -- End pasted text --
[[255 255 255 255 255 255 255 253 110   0]
 [255 255 255 255 255 255 251  95   0   0]
 [255 255 255 255 255 246  73   0   0   0]
 [255 255 255 255 247  75   0   0   0  90]
 [255 255 255 247  70   0   0   0 108 254]
 [255 255 247  68   0   0   0 136 255 255]
 [255 251  82   0   0   0 127 255 255 255]
 [255  97   0   0   0 118 255 255 255 255]
 [127   0   0   0 119 255 255 255 255 255]
 [  1   0   0  91 254 255 255 255 255 255]]
```

Output in CairoCFFI
```
ValueError                                Traceback (most recent call last)
<ipython-input-7-7cdc9a0244d0> in <module>()
      3 data = numpy.zeros((200, 200, 4), dtype=numpy.uint8)
      4 surface = cairo.ImageSurface.create_for_data(
----> 5     data, cairo.FORMAT_ARGB32, 200, 200)
      6 cr = cairo.Context(surface)
      7 

/mnt/data/home/stu/.virtualenvs/tmp/local/lib/python2.7/site-packages/cairocffi/surfaces.pyc in create_for_data(cls, data, format, width, height, stride)
    658 
    659         """
--> 660         return cls(format, width, height, data, stride)
    661 
    662     @staticmethod

/mnt/data/home/stu/.virtualenvs/tmp/local/lib/python2.7/site-packages/cairocffi/surfaces.pyc in __init__(self, format, width, height, data, stride)
    647             if length < stride * height:
    648                 raise ValueError('Got a %d bytes buffer, needs at least %d.'
--> 649                                  % (length, stride * height))
    650             pointer = cairo.cairo_image_surface_create_for_data(
    651                 ffi.cast('char*', address), format, width, height, stride)

ValueError: Got a 200 bytes buffer, needs at least 160000.
```

**Comment by stuaxo** [comment]
Will keep poking at pycairo ... interested to see if it's possible via numpy mmap to share the data behind the cairo surface between processes with zero memory copies..

**Comment by SimonSapin** [comment]
The problem lies in this function in `cairocffi/surfaces`:

```python
def from_buffer(obj):
    """Return ``(pointer_address, length_in_bytes)`` for a buffer object."""
    if hasattr(obj, 'buffer_info'):
        # Looks like a array.array object.
        address, length = obj.buffer_info()
        return address, length * obj.itemsize
    else:
        # Other buffers.
        # XXX Unfortunately ctypes.c_char.from_buffer
        # does not have length information,
        # and we’re not sure that len(obj) is measured in bytes.
        # (It’s not for array.array, though that is taken care of.)
        return ctypes.addressof(ctypes.c_char.from_buffer(obj)), len(obj)
```

As the comment says, we take `len(obj)` and assume it returns a number of bytes. For numpy arrays, it seems to the number of items in the first dimension, and not at all the number of bytes.

I’m not familiar with numpy. Can you suggest how to find out the size in bytes of the buffer backing a numpy array, regardless of it’s "shape"? (Number of dimension or size of each item.)

A better alternative, rather to specialize for a bunch of specific types, would be to do what pycairo does and use the `len` field of [the `Py_buffer` struct](https://docs.python.org/2/c-api/buffer.html#c.Py_buffer), but right know I don’t see how to get to it from ctypes or CFFI, without compiling C code. Any suggestion?

**Comment by stuaxo** [comment]
I'm not super familiar with numpy ... I had a look and there is a '.size' field which seems correct.

It might be worth having a look at the changes that numpypy does to support numpy on pypy.   I'll have a bit more of a look... you would think there was a way to get the underlying buffer.

Can see why you wouldnt want to specialise for a bunch of types, though if it comes to it numpy is a fairly popular one.

This looks fairly useful:
http://stackoverflow.com/questions/16276268/how-to-pass-a-numpy-array-into-a-cffi-function-and-how-to-get-one-back-out

At the moment I'm still sketchy on how cairo lays out it's images (is it just one big buffer, or seperate ones based on the stride) and similarly for numpy.

**Comment by stuaxo** [comment]
Some info on the numpy array interface...

http://docs.scipy.org/doc/numpy/reference/arrays.interface.html

Will see if I can use any of these to get the earlier examples working..

**Comment by SimonSapin** [comment]
CFFI also recently added [`from_buffer()`](https://bitbucket.org/cffi/cffi/issue/47/creating-a-cdata-from-a-buffer) precisely for this kind of thing. I need to look into it, but I have a feeling it’s the way to go.

----

> At the moment I'm still sketchy on how cairo lays out it's images (is it just one big buffer, or seperate ones based on the stride)

It is one big buffer, but the stride (memory offset between rows) can be larger than width times size for one pixel. The stride is also rounded up to be a multiple of four bytes (or something like that) when you let cairo pick one, but I don’t know if other values are supported when you specify the `stride` parameter.

See the documentation for pixel formats, for the `ImageSurface` constructor, and `format_stride_for_width`.

http://pythonhosted.org/cairocffi/api.html#format
http://pythonhosted.org/cairocffi/api.html#cairocffi.ImageSurface
http://pythonhosted.org/cairocffi/api.html#cairocffi.ImageSurface.format_stride_for_width

**Comment by stuaxo** [comment]
I had a go at ammending from_buffer(obj) like the following - but I then
there were a bunch of other errors in cairocffi - I'm still pretty new to numpy internals, cairo internals, ctypes and cffi though ;)

```python
def from_buffer(obj):
    """Return ``(pointer_address, length_in_bytes)`` for a buffer object."""
    if hasattr(obj, 'buffer_info'):
        # Looks like a array.array object.
        address, length = obj.buffer_info()
        return address, length * obj.itemsize
    elif hasattr(obj, '__array_interface__'):
        address, length = obj.__array_interface__['data'][0], obj.size
        return address, length
    else:
        # Other buffers.
        # XXX Unfortunately ctypes.c_char.from_buffer
        # does not have length information,
        # and we’re not sure that len(obj) is measured in bytes.
        # (It’s not for array.array, though that is taken care of.)
        return ctypes.addressof(ctypes.c_char.from_buffer(obj)), len(obj)
```

**Comment by SimonSapin** [comment]
Alright, I have this branch that uses CFFI’s new `from_buffer`. Could you try it on your numpy example? Unfortunately the feature is not in a PyPI release of CFFI yet, so you’ll need both of these:

```
pip install --upgrade hg+https://bitbucket.org/cffi/cffi
pip install --upgrade git+https://github.com/SimonSapin/cairocffi@cffi-from-buffer

**Comment by SimonSapin** [comment]
If it doesn’t work, check whether `cairocffi.surfaces.CFFI_HAS_FROM_BUFFER` is true.

**Comment by stuaxo** [comment]
Somehow I missed this at the time.   Just tested in a fresh virtualenv and it works :)

**Comment by ericwudocomoi** [comment]
Got myself a quick fix for the example above (but I do not consider other dtype), in case someone else is interested. 
In "surfaces.py", some modifications:

```Python
def from_buffer(obj):
    """Return ``(pointer_address, length_in_bytes)`` for a buffer object."""
    if hasattr(obj, 'buffer_info'):
        # Looks like a array.array object.
        address, length = obj.buffer_info()
        return address, length * obj.itemsize
    elif 'numpy.ndarray' in str(type(obj)): # this is the fix for numpy
        shape = obj.shape
        size = shape[0]*shape[1]*shape[2]
        return obj.__array_interface__['data'][0], size
    else:
        # Other buffers.
        # XXX Unfortunately ctypes.c_char.from_buffer
        # does not have length information,
        # and we’re not sure that len(obj) is measured in bytes.
        # (It’s not for array.array, though that is taken care of.)
        return ctypes.addressof(ctypes.c_char.from_buffer(obj)), len(obj)
```
In "__init__()" of class Surface:
```Python
def __init__(self, pointer, target_keep_alive=None):
    self._pointer = ffi.gc(pointer, cairo.cairo_surface_destroy)
    self._check_status()
    if target_keep_alive is not None and target_keep_alive is not ffi.NULL:  #fix for numpy case
        keep_alive = KeepAlive(target_keep_alive)
        _check_status(cairo.cairo_surface_set_user_data(
            self._pointer, SURFACE_TARGET_KEY, *keep_alive.closure))
        keep_alive.save()
```

**Comment by akiross** [comment]
Sorry if I misunderstood, but using cairocffi the issue is not solved: I still cannot make the example above work, and I cannot see changes in the `from_buffer` version.

What is the correct way to build a cairocffi surface from a numpy array?

**Comment by xy-23** [comment]
I have the same problem...
