### ISSUE TITLE
Use cairocffi to double_buffer in Gtk3 drawing area

### ISSUE THREAD

**Issue by stuaxo** [SimonSapin/cairocffi#54]
I'm trying to port some pygtk code to Gtk3 with gi.repository.    I use an ImageSurface as a double buffer.   It looks like last time I tried this I could use ```cairocffi.utils.pycairo_to_cairocffi._UNSAFE_pycairo_context_to_cairocffi``` to avoid

``` 
Traceback (most recent call last):
  File "/mnt/data/home/stu/projects/mine/shoebot/shoebot/gui/gtk_drawingarea.py", line 91, in draw
    cr.set_source_surface(self.backing_store)
TypeError: must be cairo.Surface, not ImageSurface
``` 

Whats the best way of approaching this now ?

**Comment by SimonSapin** [comment]
Assuming that `cr.set_source_surface` is from `gi`, it probably expects a pycairo surface. So in this specific case you want to convert from cairocffi to pycairo, not the reverse.

**Comment by stuaxo** [comment]
Excellent, that worked :)

While I was trying to do this the wrong way, I noticed that there are some non ascii apostrophes on line 20 + 28 comments in here:

https://github.com/SimonSapin/cairocffi/blob/f5e1f2cf27f3cebfdecb60c9c32c12dd35de141c/utils/cairocffi_to_pycairo.py

Which makes the file not run on py2 on my machine.  It's worth changing them to '

**Comment by SimonSapin** [comment]
Ugh. Does 138b63f0c559eb9dc765b44f5efd15fac0f27f86 help? Anyway this file was intended more to be copied/pasted rather than being imported directly, but whatever works for you.

**Comment by stuaxo** [comment]
Yup, should do ...  - I'll double check this later.   I'd test it on windows before being sure it works though.

I've got a lot further in porting things, but hit another conversion wall - I use 'set_matrix' in quite a few places, and can either output to cairocffi or gi (which needs a cairo.Matrix, not a cairocffi.matrix.Matrix)..   is there any way to convert these ?

**Comment by SimonSapin** [comment]
Both `Matrix` types are iterable (yielding floats) and take the same number of float parameters in their constructor. So `Matrix(*m)` should work to convert either way.

**Comment by SimonSapin** [comment]
By the way, feel free to push on https://bugzilla.gnome.org/show_bug.cgi?id=707196

**Comment by stuaxo** [comment]
Will open another ticket if I find the UTF-8 stuff doesn't work... in the meantime shutting this since you answered the question :)
