### ISSUE TITLE
`import cairocffi` errors on Windows

### ISSUE THREAD

**Issue by bmer** [SimonSapin/cairocffi#57]
Hi,

I have installed `cairo` on my Windows 8 machine by getting the necessary DLLs from the GTK project, [as per the instructions in the `cairo` documentation](http://cairographics.org/download/).

I put the DLLs supplied from that page into my `System32` folder.

Then, I used `pip` to install `cairocffi`.

When I try to run a script only with `import cairocffi`, I get the following error:

```python
    import cairocffi
  File "A:\Anaconda\lib\site-packages\cairocffi\__init__.py", line 41, in <module>
    cairo = dlopen(ffi, *CAIRO_NAMES)
  File "A:\Anaconda\lib\site-packages\cairocffi\__init__.py", line 34, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "A:\Anaconda\lib\site-packages\cffi\api.py", line 127, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "A:\Anaconda\lib\site-packages\cffi\api.py", line 572, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "A:\Anaconda\lib\site-packages\cffi\api.py", line 561, in _load_backend_lib
    return backend.load_library(name, flags)
OSError: cannot load library libcairo.so.2: error 0x7e
```

Why is this happening?

**Comment by SimonSapin** [comment]
What is the exact name of the DLL file? Is it one of [these](https://github.com/SimonSapin/cairocffi/blob/138b63f0c559eb9dc765b44f5efd15fac0f27f86/cairocffi/__init__.py#L39-L40)? (Namely `libcairo-2.dll`, probably.) What’s the output of `import os; print(os.environ['PATH'])`? Is the DLL file in one of those directories? Can you make `import cffi; cffi.FFI().dlopen('something.dll')` work for some other cairo-related value of `something`?

**Comment by bmer** [comment]
> What is the exact name of the DLL file? Is it one of these?

**Comment by SimonSapin** [comment]
Random idea: is your Python 32-bit or 64-bit? Does this match your cairo DLLs?

Other than this I don’t know what else to suggest, sorry. I don’t use Windows myself.

**Comment by SimonSapin** [comment]
More precisely, if you have a `libcairo-2.dll` file in a directory that’s in `$PATH` for the same architecture (32 vs 64-bit) as your Python and `import cffi; cffi.FFI().dlopen('libcairo-2.dll')` doesn’t work, there is some other issue on your system that I don’t understand and that is probably not a bug in cairocffi.

**Comment by bmer** [comment]
My Python is 64-bit. Based on your suggestion, I cleared up all installed DLLs, and then got the 64-bit versions (again, from the GTK project), and put them into a special folder ("cairo_dlls") which I then added to the path. I still get the same error.

```
  File "A:\Anaconda\lib\site-packages\cffi\api.py", line 567, in _load_backend_lib
    return backend.load_library(path, flags)

OSError: cannot load library A:\cairo_dlls\libcairo-2.dll: error 0x7e
```

> Other than this I don’t know what else to suggest, sorry. I don’t use Windows myself.

Okay, makes sense. I will just switch to my Ubuntu installation :)
