### ISSUE TITLE
Use CFFI’s out-of-line declarations

### ISSUE THREAD

**Issue by SimonSapin** [SimonSapin/cairocffi#59]
See https://github.com/SimonSapin/cairocffi/issues/58#issuecomment-108104743

@flacjacket, does this also work if the end-user doesn’t have a C compiler? (As is typical on Windows.) This is the main reason for using `ffi.dlopen()` over `ffi.verify()` in pre-1.0 CFFI.

**Comment by flacjacket** [comment]
Yes, the out-of-line use of cffi has the same distinction between running with or without a C compiler. The arguments passed to `ffi.set_source()` determine which method will be used (`ffi.set_source("_ffi", None)` vs `ffi.set_source("_ffi", "\\ C code")`), and I kept with the dlopen version in #60.
