### ISSUE TITLE
cairocffi 0.7 fails to install when cffi<1.0 is installed

### ISSUE THREAD

**Issue by pwelzel** [SimonSapin/cairocffi#64]
cairocffi 0.7 fails to be installed by pip when cffi<=1.0 is currently installed on the system, throwing the following error:

```
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/cairocffi/setup.py", line 57, in <module>
        **cffi_args
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 277, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
    ImportError: No module named setuptools_ext
```

Here is a Dockerfile to reproduce:
```
FROM ubuntu:trusty

RUN apt-get update && apt-get -y --no-install-recommends install \
    build-essential \
    libffi-dev \
    python2.7 \
    python-dev \
    python-pip

RUN pip install --upgrade \
    "cffi<1.0"

RUN pip install --upgrade \
    cairocffi
```

The problem is slightly annoying as at least Ubuntu (both recent TLS and normal versions) ship a python-cffi (and also python3-cffi) version below 1.0 - which is nice to avoid the need for a compiler to be installed. Anyway, I think it should not fail, if an older version is currently installed.

**Comment by SimonSapin** [comment]
Hi! Thanks for the bug report. I tried something that seems to work for me locally in a virtualenv: d9d1ef3e5a8f44a4445cd5751188d2126211ba3d could you try to install from git (`pip install git+https://github.com/SimonSapin/cairocffi`) and see if it fixes the issue for you? If so, I’ll publish 0.7.1 on PyPI.

**Comment by pwelzel** [comment]
Hi. I run it with several version (<1.0, between 1.0 and 1.1 and above 1.1) and it seems to work. Thanks for fixing it so quickly!

**Comment by SimonSapin** [comment]
https://pypi.python.org/pypi/cairocffi/0.7.1
