### ISSUE TITLE
Tracking down a leak drawing ImageSurface on Gtk3

### ISSUE THREAD

**Issue by stuaxo** [SimonSapin/cairocffi#75]
I have memory leak that occurs when I use cairocffi with shoebot.   Unfortunately some of the code is a little bit crufty, so I haven't managed to make a seperate case that demonstrates it.

(self.imagesurface was created from a png file of 1000x1186

If I have ctx.set_source_surface(self._imagesurface) then the leak occurs, but if I comment it out there is none.

https://github.com/shoebot/shoebot/blob/master/shoebot/data/img.py#L125

Any idea what could be keeping the imagesurfaces in memory ?

I tried using https://pythonhosted.org/Pympler/muppy.html to get some output each frame but couldn't see anything of use on the python side, while the numbers in top quickly head up into the GB range..  (it stops going up if I stop it rendering new frames).

**Comment by SimonSapin** [comment]
I don’t have a lead to suggest, and I can’t investigate this myself at the moment, sorry. I can look into a fix if you find the cause and it’s a bug in cairocffi.

**Comment by stuaxo** [comment]
I'm not as convinced it's down to Gtk3 now - I had a WeakValueDictionary of ``` { path:  SurfaceRef( ImageSurface) }```

```python
class SurfaceRef(object):
    ''' Cannot have a weakref to a cairo surface, so wrapper is used '''
    def __init__(self, surface):
        self.surface = surface

class Image(object):

    _surface_cache = WeakValueDictionary()
    
    def __init__(self, width, height, path):
        surfaceref = self._surface_cache.get(path)
        if surfaceref:
            imagesurface = surfaceref.surface
            sw = imagesurface.get_width()
            sh = imagesurface.get_height()
        else:
            img = PILImage.open(path)

            if img.mode != 'RGBA':
                img = img.convert("RGBA")

            sw, sh = img.size
            # Would be nice to not have to do some of these conversions :-\
            bgra_data = img.tostring('raw', 'BGRA', 0, 1)
            bgra_array = array.array('B', bgra_data)
            imagesurface = cairo.ImageSurface.create_for_data(bgra_array, cairo.FORMAT_ARGB32, sw, sh, sw*4)

        self._surface_cache[path] = SurfaceRef(imagesurface)

```

Interestingly, I'm not sure it was doing much good - at each frame it seems like the WeakValueDictionary was evicting my surfaces and the cache was empty, the memory was still leaking somewhere though.

For now, I've switched to a plain dict, which seems to stop the leak.    I'll see if I can get time to confirm this / turn it into some sort of test script.

**Comment by stuaxo** [comment]
Going to close this as haven't managed to reproduce outside of shoebot.
